# Generated by Django 3.1 on 2020-08-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('url', models.URLField(max_length=140)),
                ('rating', models.IntegerField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
