# Generated by Django 3.1 on 2020-08-29 11:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20200829_1212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'ordering': ['name'], 'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterField(
            model_name='courses',
            name='name',
            field=models.CharField(max_length=140, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='url',
            field=models.URLField(max_length=140, unique=True, verbose_name='Ссылка'),
        ),
    ]
